apiVersion : apps/v1
kind: Deployment
metadata:
  name: gjuly23image1 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: gjuly23image1
  template:
    metadata:
      labels:
        app: gjuly23image1 
    spec:
      containers:
        - name: gjuly23image1 
          image: newssep06.azurecr.io/goct11image
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: gjuly23image1
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: gjuly23image1
